### ISSUE TITLE
Dataset Issue about WIKIDATA114k

### ISSUE THREAD

**Issue by Cantoria** [ling-cai/Time2Box#1]
Hi Dear Cai,
I'm interested in your research work Time2Box. However, I don't find the dataset WIKIDATA114k in your paper or the repo. Would you consider open source this dataset? Thanks!

**Comment by daima2017** [comment]
I'm interested in your dataset WIKIDATA114k ，and would you like to share it?

**Comment by ling-cai** [comment]
The data is shared in google drive. Please check here: https://drive.google.com/drive/folders/1zhhhePRxodOsMQ1T9TGMF7WYlaU4i9je?usp=sharing

**Comment by Cantoria** [comment]
> The data is shared in google drive. Please check here: https://drive.google.com/drive/folders/1zhhhePRxodOsMQ1T9TGMF7WYlaU4i9je?usp=sharing

Could you provide the entity-id/relation-id/time-id files of wikidata114k? Thanks!
